132812 sanity check based on epic branch
DFE-Digital/get-information-about-schools pull request #278
Opened 2023-02-03 06:56 UTC by BarryGibney

2023-02-10 14:33 UTC, BarryGibney commented
As per ticket: 140914 - chair of governors was not receiving error messages - all error messages are showing in the relevant fields and a summary is now displayed in a banner at the top of the page - as per last checks add new governance professional is not displaying this - so converted to draft to update

2023-02-13 09:53 UTC, ScottDawsonDfE requested changes

2023-02-13 09:53 UTC, ScottDawsonDfE commented on Web/Edubase.Web.UI/Views/Shared/EditorTemplates/GovernorViewModel.cshtml
>              <label class="govuk-label" for="GovernorTelephoneNumberInput">
for needs updating to match the id of the label it is for - just TelephoneNumber here

2023-02-13 09:53 UTC, ScottDawsonDfE commented on Web/Edubase.Web.UI/Views/Shared/EditorTemplates/GovernorViewModel.cshtml
>                  </a>
Line 128 - for needs updating to be just Postcode

Check for any other instances of this

2023-02-13 20:59 UTC, ScottDawsonDfE approved these changes

2023-02-13 21:08 UTC, merged